spring:
  datasource:
#    url: "jdbc:h2:d:/projects/test-task/sql/app_db"
    url: "jdbc:h2:~/sql/app_db"
    username: superuser
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
